name: ci

on:
  pull_request:

env:
  NWAKU_VERSION: "v0.9"

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get nwaku
        shell: bash
        run: |
          mkdir -p nwaku/build
          cd nwaku
          wget "https://github.com/status-im/nwaku/releases/download/${NWAKU_VERSION}/nim-waku-ubuntu-latest.tar.gz"
          tar xavf nim-waku-ubuntu-latest.tar.gz
      - name: Run wakunode2 with no options
        shell: bash
        run: |
          uname -a
          cd nwaku/build
          (timeout --signal=SIGINT 30s ./wakunode2 || true)
      
