name: Test Windows

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        env:
          - { NPROC: 2 }
          - { NPROC: 6 }
    runs-on: windows-latest
    env: ${{ matrix.env }}

  name: windows - ${{ matrix.env.NPROC }} processes

  steps:
    - uses: eine/setup-msys2@v0
      with:
          msystem: MSYS
          update: true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% CI_CACHE=NimBinaries update
        mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% fetch-dlls

    - name: Run Tests
      run: |
        mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% LOG_LEVEL=TRACE
        build\wakunode.exe --help
        mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% test
