name: test-workflows

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NPROC: 2
  MAKEFLAGS: "-j${NPROC}"
  NIMFLAGS: "--parallelBuild:${NPROC} --colors:off -d:chronicles_colors:none"

jobs:
  js-waku-node-quay:
    uses: waku-org/js-waku/.github/workflows/test-node.yml@master
    with:
      nim_wakunode_image: quay.io/wakuorg/nwaku-pr:2690-rln-v1
      test_type: node
      debug: waku*
  
  js-waku-node-release:
    uses: waku-org/js-waku/.github/workflows/test-node.yml@master
    with:
      nim_wakunode_image: wakuorg/nwaku:v0.27.0
      test_type: node
      debug: waku*
