# This workflow is temporary till zerokit rln is the default target
name: Test (Zerokit Enabled)

on:
  pull_request:
    paths:
      - 'waku/v2/protocol/waku_rln_relay/**'
      - '!waku/v2/protocol/waku_rln_relay/**/*.md'
  push:
    branches:
      - master
    paths:
      - 'waku/v2/protocol/waku_rln_relay/**'
      - '!waku/v2/protocol/waku_rln_relay/**/*.md'

jobs:
  zerokit_test:
    strategy:
      matrix:
        env:
          - NPROC: 2
            MAKEFLAGS: "-j${NPROC}"
            NIMFLAGS: "--parallelBuild:${NPROC}"
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    env: ${{ matrix.env }}
    timeout-minutes: 60

    name: ${{ matrix.platform }} - ${{ matrix.env.NPROC }} processes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # We need to do this because of how github cache works
        # I am not sure we can move the cache file, so if we do not do this
        # make update breaks because the cached compiler is there where the submodules
        # are meant to go.
      - name: Submodules
        run: git submodule update --init --recursive

      - name: Cache nim
        uses: actions/cache@v1
        with:
          path: vendor/nimbus-build-system/vendor/Nim/bin
          key: ${{ runner.os }}-${{ matrix.env.NPROC }}-nim-${{ hashFiles('.gitmodules') }}

      - name: Update dependencies
        run: make V=1 update

      - name: Build V2 binaries with zerokit enabled
        run: make LOG_LEVEL=TRACE ONCHAIN_RLN=true RLNZEROKIT=true v2

      - name: Run V2 Tests with zerokit enabled
        run: make ONCHAIN_RLN=true RLNZEROKIT=true test2
